#!/bin/bash
# Video Background
#
# By Gethyn "Xylemon" ThomasQuail
#
# Load video files like this "videobackground /path/to/file".

# Loads configuration file.
c_file=~/.xyscripts

source $c_file
echo "File Loaded"

xwinwrap -ov -g $RES -- $PLAY $REND -wid WID $1 $VPARM
